version: 0.2

# aws codebuild start-build --project-name moar
phases:
  pre_build:
    commands:
      - cd ${TF_DIR}
  install:
    commands:
      - yarn install --frozen-lockfile --offline --check-files --cache-folder ./cache
      - |
        if [ ${CLIENT} = "studio" ] ; then
          rm -rf node_modules/sharp;
          SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc sharp;
        fi
      - yarn run build
artifacts:
  secondary-artifacts:
    BuildArtifact:
      files:
        - "**/*"
      exclude-paths:
        - ./deployment
    BuildDistArtifact:
      files:
        - "**/*"
      base-directory: dist
