version: 0.2

# aws codebuild start-build --project-name moar
phases:
  pre_build:
    commands:
      - cd ${TF_DIR}
  install:
    commands:
      - find -name "package.json" | awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2- | sed -e '/.\/node_modules\//d' -e 's/package.json//' | xargs -iX bash -c "echo Installing to X && yarn install --frozen-lockfile --cache-folder $PWD/cache --cwd X"
      - |
        if [ "${CLIENT}" == "studio" ] ; then
          cd infrastructure/deployment_module/lambdas_code/appsync/moar-manage-images
          rm -rf node_modules/sharp;
          SHARP_IGNORE_GLOBAL_LIBVIPS=1 yarn add --arch=x64 --platform=linux --libc=glibc sharp@0.32.3;
        fi
artifacts:
  secondary-artifacts:
    BuildArtifact:
      files:
        - "**/*"
      exclude-paths:
        - ./deployment
    BuildDistArtifact:
      files:
        - "**/*"
      base-directory: dist
