version: 0.2

# aws codebuild start-build --project-name moar
phases:
  install:
    commands:
      - yarn install --frozen-lockfile --offline --check-files --cache-folder ./cache
  build:
    commands:
      - ls
      - yarn run build
artifacts:
  files:
    - "**/*"
  exclude-paths:
    - ./**/infrastructure
