version: 0.2

# aws codebuild start-build --project-name moar
phases:
  install:
    on-failure: ABORT
    commands:
      - yarn install
  build:
    commands:
      - ls
      - yarn run build
artifacts:
  files:
    - "**/*"
  exclude-paths: 
    - ./**/infrastructure